// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeHhN6tYLsaKRfNUaxYpMJbDDYa9sA0X0',
    appId: '1:683993713589:android:a6227d38d6f4b45408e7fc',
    messagingSenderId: '683993713589',
    projectId: 'event-planner-bad3f',
    storageBucket: 'event-planner-bad3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh50mZ_IAfxWu8Htj-NF1P6WHL1i5n1eQ',
    appId: '1:683993713589:ios:9fbff635534fcc2108e7fc',
    messagingSenderId: '683993713589',
    projectId: 'event-planner-bad3f',
    storageBucket: 'event-planner-bad3f.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanner',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl8aFEvTOgmRfMVVDoUcd0kBpYBuE_4vE',
    appId: '1:683993713589:web:0e64df6e75fdb5fa08e7fc',
    messagingSenderId: '683993713589',
    projectId: 'event-planner-bad3f',
    authDomain: 'event-planner-bad3f.firebaseapp.com',
    storageBucket: 'event-planner-bad3f.firebasestorage.app',
    measurementId: 'G-92KCWKTH55',
  );

}